### ISSUE TITLE
Update operator to use latest router image ? 

### ISSUE THREAD

**Issue by jlammsm** [skupperproject/skupper-operator#15]
Hi, 

I'm trying to use the operator in my eks cluster following the instructions. When i apply `examples/skupper-site-interior.yaml` it creates a skupper router but it fails to pull down the image as its using
quay.io/skupper/skupper-router@sha256:e563f069635fbabe4080770107defcd15d10125aa2f1e0747f118942efe9f9b8
which doesnt seem to exist ? 

Is there a way you can update this?

Thanks

**Comment by fgiorgetti** [comment]
It should be fixed now in version 1.1.1.
