### ISSUE TITLE
Missing "routes/custom-host" resource in ClusterRole

### ISSUE THREAD

**Issue by trumbaut** [skupperproject/skupper-operator#21]
Skupper allows setting a hostname for routes using the `data:ingress-host` parameter in the `skupper-site` [ConfigMap](https://github.com/skupperproject/skupper/blob/master/cmd/site-controller/README.md#managing-a-skupper-site-using-configmaps). However, currently this doesn't work in OCP (`skupper-operator.v1.2.2-74cbf46bbc`) due to missing ClusterRole permissions. As a result, setting the `data:ingress-host` parameter breaks initialising the site with following errors in the site controller pod:

```
2023/04/07 09:49:53 Initialising skupper site ...
2023/04/07 09:49:54 Error initialising skupper: Route.route.openshift.io "skupper-inter-router" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route
E0407 09:49:54.785647 1 controller.go:168] Route.route.openshift.io "skupper-inter-router" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route
```

To fix this, we simply need to add `routes/custom-host` as a resource for the ClusterRole (https://github.com/skupperproject/skupper-operator/blob/main/bundle/manifests/1.3.0/skupper-operator.v1.3.0.clusterserviceversion.yaml#L68):

```
[...]
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
[...]
```

Let me know if/where I can create a PR for this.

**Comment by fgiorgetti** [comment]
@trumbaut makes sense to me. 
@grs @ajssmith @nluaces thoughts?

**Comment by grs** [comment]
Yes, makes sense to me also

**Comment by fgiorgetti** [comment]
@trumbaut could you please submit a PR with the proposed change?
You have to do it against the [Skupper repository](https://github.com/skupperproject/skupper/).

**Comment by trumbaut** [comment]
@fgiorgetti : I fixed this in https://github.com/trumbaut/skupper-operator/commit/ef56c2d640b993981944106f1daa0645f4ac879b but how can I submit it against the [Skupper repository](https://github.com/skupperproject/skupper/)?

**Comment by trumbaut** [comment]
@fgiorgetti, please check the PR's above.
